[package]
name = "ogcapi-drivers"
version = "0.1.3"
description = "Driver traits and implementations"
license = "MIT OR Apache-2.0"
repository = "https://github.com/camptocamp/ogcapi"
edition = "2021"

include = ["/src", "/migrations"]

[features]
s3 = ["aws-config", "aws-sdk-s3"]
stac = ["ogcapi-types/stac"]
postgres = ["sqlx", "rink-core", "url"]

[dependencies]
anyhow = "1.0.58"
aws-config = { version = "0.46.0", optional = true }
aws-sdk-s3 = { version = "0.16.0", optional = true }
async-trait = "0.1.56"
http = "0.2.8"
rink-core = { version = "0.6.2", optional = true }
serde_json = "1.0.82"
sqlx = { version = "0.6.0", optional = true, features = ["runtime-tokio-rustls", "postgres", "json"] }
tokio = { version = "1.20.1", features = ["full"] }
url = { version = "2.2.2", optional = true }

# ogcapi-types = "0.1.0"
ogcapi-types = { path = "../ogcapi-types" }
