[package]
name = "ogcapi"
version = "0.1.0"
description = "OGC API building blocks."
license = "MIT OR Apache-2.0"
repository = "https://github.com/camptocamp/ogcapi"
edition = "2021"

[features]
default = ["types", "client", "drivers", "services", "import"]

client = ["ogcapi-client"]
drivers = ["ogcapi-drivers"]
services = ["ogcapi-services", "ogcapi-services/full"]
types = ["ogcapi-types"]

import = ["gdal", "geo", "geojson", "osmpbfreader", "serde", "serde_json", "sqlx", "url", "wkb"]

stac = ["ogcapi-types?/stac", "ogcapi-drivers?/stac", "ogcapi-drivers?/s3", "ogcapi-services?/stac"]

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.15", features = ["derive", "env"] }
dotenv = { version = "0.15.0" }
gdal = { version = "0.12.0", optional = true, features = ["bindgen"] }
geo = { version = "0.22.1", optional = true }
geojson = { version = "0.23.0", optional = true, features = ["geo-types"] }
osmpbfreader = { version = "0.15.2", optional = true }
serde = { version = "1.0.140", optional = true }
serde_json = { version = "1.0.82", optional = true }
sqlx = { version = "0.6.0", optional = true, features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.20.1", features = ["full"] }
tracing = { version = "0.1.35"}
tracing-subscriber = { version="0.3.15", features = ["env-filter"] }
url = { version = "2.2.2", optional = true, features = ["serde"] }
wkb = { version = "0.7.1", optional = true }

# ogcapi-types = { version = "0.1.0", optional = true }
# ogcapi-drivers = { version = "0.1.3", optional = true }
# ogcapi-services = { version = "0.1.2", optional = true }
# ogcapi-client = { version = "0.1.0", optional = true }
ogcapi-types = { path = "../ogcapi-types", optional = true }
ogcapi-drivers = { path = "../ogcapi-drivers", optional = true }
ogcapi-services = { path = "../ogcapi-services", optional = true }
ogcapi-client = { path = "../ogcapi-client", optional = true }
