[package]
name = "ogcapi-client"
version = "0.1.0"
description = "Client to access OGC API Feature and STAC endpoints."
license = "MIT OR Apache-2.0"
repository = "https://github.com/camptocamp/ogcapi"
edition = "2021"

[features]
default = []
stac = ["ogcapi-types/stac"]

[dependencies]
geojson = "0.23.0"
once_cell = "1.13.0"
reqwest = { version = "0.11.11", default-features = false, features = ["json", "blocking", "rustls-tls", "hyper-rustls"] }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
serde_qs = "0.10.1"
thiserror = "1.0.31"
url = { version = "2.2.2", features = ["serde"]}

# ogcapi-types = "0.1.0"
ogcapi-types = { path = "../ogcapi-types" }